<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Notifications</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" Version="4.17.0" />
        <PackageReference Include="MassTransit" Version="8.5.10" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.10" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
        <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Pharmacy.Event\Pharmacy.Event.csproj" />
    </ItemGroup>

</Project>
